server:
  port: 8891
spring:
  application:
    name: springcloud-config-server
  cloud: 
    config: 
      label: master
      username:                                             # git仓库的账号
      password:                                             # git仓库的密码
      server: 
        git:
          uri: https://github.com/WangPan001/personalGit/     # 配置git仓库的地址
          search-paths: respo                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          force-pull: true #设置强行pull拉取
eureka: 
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8890/eureka
